src/SuProfile/BlogBundle/Entity/Image.php
<?php

namespace SuProfile\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="SuProfile\BlogBundle\Entity\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
	/**
	* @ORM\Column(name="id", type="integer")
	* @ORM\Id
	* @ORM\GeneratedValue(strategy="AUTO")
	*/
	private $id;

	/**
	* @ORM\Column(name="url", type="string", length=255)
	*/
	private $url;
	
	/**
	* @ORM\Column(name="alt", type="string", length=255)
	*/
	private $alt;

	/**
	* @Assert\File(maxSize="500k")
	*/
	private $file;

	private $tempFilename;

	/**
	* @ORM\PrePersist()
	* @ORM\PreUpdate()
	*/
	public function preUpload()
	{
		if (null === $this->file) {
			return;
		}
		
		$this->url = $this->file->guessExtension();

		$this->alt = $this->file->getClientOriginalName();
	}

	/**
	* @ORM\PostPersist()
	* @ORM\PostUpdate()
	*/
	public function upload()
	{
		if (null === $this->file) {
			return;
		}

		if (null !== $this->tempFilename) {
			$oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
			if (file_exists($oldFile)) {
				unlink($oldFile);
			}
		}

		$this->file->move(
		$this->getUploadRootDir(),
		$this->id.'.'.$this->url
		);
	}

	/**
	* @ORM\PreRemove()
	*/
	public function preRemoveUpload()
	{
		$this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
	}

	/**
	* @ORM\PostRemove()
	*/
	public function removeUpload()
	{
		if (file_exists($this->tempFilename)) {
			unlink($this->tempFilename);
		}
	}

	public function getUploadDir()
	{
		return 'uploads/img';
	}

	public function getUploadRootDir()
	{
		return __DIR__.'/../../../../web/'.$this->getUploadDir();
	}

	public function getWebPath()
	{
		return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
	}
	
	public function getFullImagePath() {
        return null === $this->image ? null : $this->getUploadRootDir(). $this->image;
    }

	/**
	* @return integer
	*/
	public function getId()
	{
		return $this->id;
	}

	/**
	* @param string $url
	* @return Image
	*/
	public function setUrl($url)
	{
		$this->url = $url;
		return $this;
	}

	/**
	* @return string
	*/
	public function getUrl()
	{
		return $this->url;
	}

	/**
	* @param string $alt
	* @return Image
	*/
	public function setAlt($alt)
	{
		$this->alt = $alt;
		return $this;
	}

	/**
	* @return string
	*/
	public function getAlt()
	{
		return $this->alt;
	}

	public function setFile($file)
	{
		$this->file = $file;

		if (null !== $this->url) {
			$this->tempFilename = $this->url;

			$this->url = null;
			$this->alt = null;
		}
	}

	public function getFile()
	{	
		return $this->file;
	}
}

src/SuProfile/BlogBundle/Controller/BlogController.php
<?php

namespace SuProfile\BlogBundle\Controller;
 
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\Form\Form;

use SuProfile\BlogBundle\Entity\Article;
use SuProfile\BlogBundle\Entity\Categorie;
use SuProfile\BlogBundle\Entity\Commentaire;
use SuProfile\BlogBundle\Entity\Image;
use SuProfile\BlogBundle\Entity\Fichier;
use SuProfile\BlogBundle\Entity\Suprofile;
use SuProfile\BlogBundle\Entity\B1;
use SuProfile\BlogBundle\Entity\B2;
use SuProfile\BlogBundle\Entity\B3;
use SuProfile\BlogBundle\Entity\M1;
use SuProfile\BlogBundle\Entity\M2;

use SuProfile\BlogBundle\Form\ArticleType;
use SuProfile\BlogBundle\Form\ArticleEditType;
use SuProfile\BlogBundle\Form\ArticleDownloadType;
use SuProfile\BlogBundle\Form\CommentaireType;
use SuProfile\BlogBundle\Form\SuprofileType;
use SuProfile\BlogBundle\Form\SuprofileEditType;

 
class BlogController extends Controller
{
	public function indexAction()
	{
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
			return $this->render('SuProfileBlogBundle:Blog:index.html.twig');
		}
		else{
			return $this->redirect($this->generateUrl('fos_user_security_login'));
		}
	}
  
	public function cateAction($cate, $page)
	{
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
			$nbParPage = 5;

			$articles = $this->getDoctrine()
							 ->getManager()
							 ->getRepository('SuProfileBlogBundle:Article')
							 ->getArticles($nbParPage, $page, $cate);


			return $this->render('SuProfileBlogBundle:Blog:cate.html.twig', array(
			'articles' => $articles,
			'cate'     => $cate,
			'page'     => $page,
			'nb_page'  => ceil(count($articles) / $nbParPage) ?: 1
			));
		}
		else{
			return $this->redirect($this->generateUrl('fos_user_security_login'));
		}
	}
	
	public function dlAction($page)
	{
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
			$nbParPage = 5;

			$articles = $this->getDoctrine()
							 ->getManager()
							 ->getRepository('SuProfileBlogBundle:Article')
							 ->getDownloads($nbParPage, $page);


			return $this->render('SuProfileBlogBundle:Blog:dl.html.twig', array(
			'articles' => $articles,
			'page'     => $page,
			'nb_page'  => ceil(count($articles) / $nbParPage) ?: 1
			));
		}
		else{
			return $this->redirect($this->generateUrl('fos_user_security_login'));
		}
	}
	
	public function monSuprofileAction($page)
	{
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
			$nbParPage = 5;
			$userId = $this->get('security.context')->getToken()->getUser()->getId();
			
			$suprofiles = $this->getDoctrine()
							 ->getManager()
							 ->getRepository('SuProfileBlogBundle:Suprofile')
							 ->getSuprofile($userId, $nbParPage, $page);


			return $this->render('SuProfileBlogBundle:Blog:monSuprofile.html.twig', array(
			'suprofiles' => $suprofiles,
			'page'     => $page,
			'nb_page'  => ceil(count($suprofiles) / $nbParPage) ?: 1,
			'userId'   => $userId
			));
		}
		else{
			return $this->redirect($this->generateUrl('fos_user_security_login'));
		}
	}
	
	public function suprofileAction($id, $page)
	{
			$nbParPage = 5;
			$userId = $id;
			
			$suprofiles = $this->getDoctrine()
							 ->getManager()
							 ->getRepository('SuProfileBlogBundle:Suprofile')
							 ->getSuprofile($userId, $nbParPage, $page);


			return $this->render('SuProfileBlogBundle:Blog:afficherSuprofile.html.twig', array(
			'suprofiles' => $suprofiles,
			'page'     => $page,
			'nb_page'  => ceil(count($suprofiles) / $nbParPage) ?: 1
			));
	}
 
	public function voirAction(Article $article, Form $form = null)
	{
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
			$em = $this->getDoctrine()->getManager();
			$currentUser = $this->get('security.context')->getToken()->getUser()->getUsername();
			$commentaires = $em->getRepository('SuProfileBlogBundle:Commentaire')
							   ->getByArticle($article->getId());
			
			$fichier = $article->getFichier();

			if (null === $form) {
				$form = $this->getCommentaireForm($article);
			}

			return $this->render('SuProfileBlogBundle:Blog:voir.html.twig', array(
			'article'      => $article,
			'form'         => $form->createView(),
			'commentaires' => $commentaires,
			'fichier'      => $fichier,
			'currentUser'   => $currentUser
			));
		}
		else{
			return $this->redirect($this->generateUrl('fos_user_security_login'));
		}
	}
 
	public function ajouterAction()
	{
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
			$article = new Article;
	
			if ($this->getUser()) {
				$article->setUser($this->getUser());
			}
 
			$form = $this->createForm(new ArticleType(), $article);
 
			$request = $this->getRequest();
 
			if ($request->getMethod() == 'POST') {

				$form->bind($request);
 
				if ($form->isValid()) {

					$em = $this->getDoctrine()->getManager();
					$em->persist($article);
					$em->flush();
 
					$this->get('session')->getFlashBag()->add('info', 'Article bien ajouté');
 
					return $this->redirect($this->generateUrl('SuProfileblog_voir', array('slug' => $article->getSlug())));
				}
			}
 
			return $this->render('SuProfileBlogBundle:Blog:ajouter.html.twig', array(
			'form' => $form->createView(),
			));
		}
		else{
			return $this->redirect($this->generateUrl('fos_user_security_login'));
		}	
	}
	
	public function ajouterDlAction()
	{
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
			$article = new Article;
	
			if ($this->getUser()) {
				$article->setUser($this->getUser());
			}
 
			$form = $this->createForm(new ArticleDownloadType(), $article);
 
			$request = $this->getRequest();
 
			if ($request->getMethod() == 'POST') {

				$form->bind($request);
 
				if ($form->isValid()) {

					$em = $this->getDoctrine()->getManager();
					$em->persist($article);
					$em->flush();
 
					$this->get('session')->getFlashBag()->add('info', 'Fichier bien ajouté');
 
					return $this->redirect($this->generateUrl('SuProfileblog_voir', array('slug' => $article->getSlug())));
				}
			}
			$fichier = $article->getFichier();
			return $this->render('SuProfileBlogBundle:Blog:ajouter.html.twig', array(
			'form' => $form->createView(),
			'fichier' => $fichier
			));
		}
		else{
			return $this->redirect($this->generateUrl('fos_user_security_login'));
		}	
	}
	
	public function ajouterSuprofileAction()
	{
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
			$suprofile = new Suprofile;
	
			if ($this->getUser()) {
				$suprofile->setUser($this->getUser());
			}
 
			$form = $this->createForm(new SuprofileType(), $suprofile);
 
			$request = $this->getRequest();
 
			if ($request->getMethod() == 'POST') {

				$form->bind($request);
 
				if ($form->isValid()) {

					$em = $this->getDoctrine()->getManager();
					$em->persist($suprofile);
					$em->flush();
 
					$this->get('session')->getFlashBag()->add('info', 'Suprofile bien ajoutée');
 
					return $this->redirect($this->generateUrl('SuProfileblog_monSuprofile'));
				}
			}
 
			return $this->render('SuProfileBlogBundle:Blog:ajouterSuprofile.html.twig', array(
			'form' => $form->createView(),
			));
		}
		else{
			return $this->redirect($this->generateUrl('fos_user_security_login'));
		}	
	}
	
	public function modifierAction(Article $article)
	{
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
			$form = $this->createForm(new ArticleEditType(), $article);
 
			$request = $this->getRequest();
 
			if ($request->getMethod() == 'POST') {
				$form->bind($request);
 
				if ($form->isValid()) {
					$em = $this->getDoctrine()->getManager();
					$em->persist($article);
					$em->flush();
 
					$this->get('session')->getFlashBag()->add('info', 'Article bien modifié');
 
					return $this->redirect($this->generateUrl('SuProfileblog_voir', array('slug' => $article->getSlug())));
				}
			}
 
			return $this->render('SuProfileBlogBundle:Blog:modifier.html.twig', array(
			'form'    => $form->createView(),
			'article' => $article
			));
		}
		else{
			return $this->redirect($this->generateUrl('fos_user_security_login'));
		}
	}
	
	public function modifierSuprofileAction(Suprofile $suprofile)
	{
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
			$form = $this->createForm(new SuprofileEditType(), $suprofile);
 
			$request = $this->getRequest();
 
			if ($request->getMethod() == 'POST') {
				$form->bind($request);
 
				if ($form->isValid()) {
					$em = $this->getDoctrine()->getManager();
					$em->persist($suprofile);
					$em->flush();
 
					$this->get('session')->getFlashBag()->add('info', 'Suprofile bien modifiée');
 
					return $this->redirect($this->generateUrl('SuProfileblog_monSuprofile'));
				}
			}
 
			return $this->render('SuProfileBlogBundle:Blog:modifierSuprofile.html.twig', array(
			'form'    => $form->createView(),
			'suprofile' => $suprofile
			));
		}
		else{
			return $this->redirect($this->generateUrl('fos_user_security_login'));
		}
	}
 
	public function supprimerAction(Article $article)
	{
		if ($this->get('security.context')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
			$form = $this->createFormBuilder()->getForm();
 
			$request = $this->getRequest();
			if ($request->getMethod() == 'POST') {
				$form->bind($request);
 
				if ($form->isValid()) {
					$em = $this->getDoctrine()->getManager();
					$em->remove($article);
					$em->flush();
 
					$this->get('session')->getFlashBag()->add('info', 'Article bien supprimé');
 
					return $this->redirect($this->generateUrl('SuProfileblog_accueil'));
				}
			}

			return $this->render('SuProfileBlogBundle:Blog:supprimer.html.twig', array(
			'article' => $article,
			'form'    => $form->createView()
			));
		}
		else{

src/SuProfile/BlogBundle/Resources/views/Blog/afficherSuprofile.html.twig
{% extends "::layoutSuprofile.html.twig" %}

{% block body %}
	{% for suprofile in suprofiles %}
		<div class="border">
			{% include "SuProfileBlogBundle:Blog:suprofile.html.twig" %}
		</div>
	{% endfor %}
{% endblock %}

src/SuProfile/BlogBundle/Resources/views/Blog/ajouter.html.twig
{% extends "SuProfileBlogBundle::layout.html.twig" %}

{% block title %}
	Ajouter une publication - {{ parent() }}
{% endblock %}

{% block SuProfileblog_body %}
	<div class="border">
		<h3>Ajouter une publication</h3>
		
		{% include "SuProfileBlogBundle:Blog:formulaire.html.twig" %}
	</div>
{% endblock %}

src/SuProfile/BlogBundle/Resources/views/Blog/article.html.twig
{% set accueil = accueil|default(false) %}

{% if accueil %}
	<h3><a href="{{ path('SuProfileblog_voir', {'slug': article.slug} ) }}">{{ article.titre }}</a></h3>
	<div class="centre"><i>Par {{ article.user}}, le {{ article.date|date('d/m/Y') }}.</i></div></br>
{% else %}
	<h3>{{ article.titre }}</h3>
	<div class="centre"><i>Par {{ article.user}}, le {{ article.date|date('d/m/Y') }}.</i></div></br>
	{% if article.fichier is not null %}
		<div class="centre"><a class="btn btn-primary" href="{{ path('SuProfileblog_download', {'id': fichier.id}) }}">Télécharger &raquo; {{ fichier.alt }}</a></div></br>
	{% endif %}
	{% if article.image is not null %}
		<div class="centre"><img src="{{ asset(article.image.webPath) }}" alt="{{ article.image.alt }}"/></div></br>
	{% endif %}
	{% if article.video is not null %}
		<div class="centre"><a href="{{ article.video }}"></a></div></br>
	{% endif %}
	{% if article.contenu is not null %}
		<div class="well" itemprop="articleBody">
			{{ article.contenu|markdown }}
		</div>
	{% endif %}
{% endif %}

src/SuProfile/BlogBundle/Resources/views/Blog/suprofile.html.twig
{% block SuProfileblog_body %}
{% if suprofile.image is not null %}
	<img src="{{ asset(suprofile.image.webPath) }}" class="photo" alt="{{ suprofile.image.alt }}"/>
{% endif %}
<h4>SuProfile</h4></br>
{% if suprofile.nom is not null %}
	<span class="coloration">Nom :</span> {{ suprofile.nom}}</br></br>
{% endif %}
{% if suprofile.prenom is not null %}
	<span class="coloration">Prénom :</span> {{ suprofile.prenom}}</br></br>
{% endif %}
{% if suprofile.adresse is not null %}
	<span class="coloration">Adresse :</span> {{ suprofile.adresse}}</br></br>
{% endif %}
{% if suprofile.classe is not null %}
	<span class="coloration">Classe :</span> {{ suprofile.classe}}</br></br>
{% endif %}
{% if suprofile.formations is not null %}
	<span class="coloration">Formations :</span> {{ suprofile.formations}}</br></br>
{% endif %}
{% if suprofile.competences is not null %}
	<span class="coloration">Compétences :</span> {{ suprofile.competences}}</br></br>
{% endif %}
{% if suprofile.experiences is not null %}
	<span class="coloration">Expériences :</span> {{ suprofile.experiences}}</br></br>
{% endif %}

<div class="centre coloration">Mes notes :</div></br>

<table class="table table-bordered table-striped">
	<tr>
		<th><span class="coloration">Matières</span></th>
		<th><span class="coloration">B1</span></th>
		<th><span class="coloration">B2</span></th>
		<th><span class="coloration">B3</span></th>
		<th><span class="coloration">M1</span></th>
		<th><span class="coloration">M2</span></th>
	</tr>
	<tr>
		<td><span class="coloration">Agile and Scrum</span></td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.M1.MET}}</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Anglais</span></td>
		<td>{{ suprofile.B1.ENG}}</td>
		<td>{{ suprofile.B2.ENG}}</td>
		<td>{{ suprofile.B3.ENG}}</td>
		<td>{{ suprofile.M1.ENG}}</td>
		<td>{{ suprofile.M2.ENG}}</td>
	</tr>
	<tr>
		<td><span class="coloration">Assembleur</span></td>
		<td>{{ suprofile.B1.CPA}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">BI</span></td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.M1.BIS}}</td>
		<td>{{ suprofile.M2.BIS}}</td>
	</tr>
	<tr>
		<td><span class="coloration">C/C++/UML</span></td>
		<td>{{ suprofile.B1.ADS}}</td>
		<td>{{ suprofile.B2.ADS}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">C#</span></td>
		<td>-</td>
		<td>{{ suprofile.B2.NET}}</td>
		<td>{{ suprofile.B3.NET}}</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">CobiT</span></td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.M2.MET}}</span></td>
	</tr>
	<tr>
		<td><span class="coloration">Cocoa</span></td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.B3.APL}}</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Compilation</span></td>
		<td>-</td>
		<td>{{ suprofile.B2.CMP}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Cryptographie</span></td>
		<td>{{ suprofile.B1.ARI}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Data Management</span></td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.M2.DAT}}</td>
	</tr>
	<tr>
		<td><span class="coloration">Droit</span></td>
		<td>{{ suprofile.B1.LAW}}</td>
		<td>{{ suprofile.B2.LAW}}</td>
		<td>{{ suprofile.B3.LAW}}</td>
		<td>{{ suprofile.M1.LAW}}</td>
		<td>{{ suprofile.M2.LAW}}</td>
	</tr>
	<tr>
		<td><span class="coloration">Engineer Best Practices</span></td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.M2.EBP}}</td>
	</tr>
	<tr>
		<td><span class="coloration">Entrepreneurship</span></td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.M2.EPS}}</td>
	</tr>
	<tr>
		<td><span class="coloration">ERP</span></td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.M1.ERP}}</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Intelligence artificielle</span></td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.B3.AIT}}</td>
		<td>{{ suprofile.M1.AIT}}</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">ITIL</span></td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.B3.MET}}</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Java</span></td>
		<td>-</td>
		<td>{{ suprofile.B2.JVA}}</td>
		<td>{{ suprofile.B3.JVA}}</td>
		<td>{{ suprofile.M1.JVA}}</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Linux</span></td>
		<td>{{ suprofile.B1.LIN}}</td>
		<td>{{ suprofile.B2.LIN}}</td>
		<td>{{ suprofile.B3.LIN}}</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Management</span></td>
		<td>{{ suprofile.B1.MGT}}</td>
		<td>{{ suprofile.B2.MGT}}</td>
		<td>{{ suprofile.B3.MGT}}</td>
		<td>{{ suprofile.M1.MGT}}</td>
		<td>{{ suprofile.M2.MGT}}</td>
	</tr>
	<tr>
		<td><span class="coloration">Maths</span></td>
		<td>{{ suprofile.B1.MAT}}</td>
		<td>{{ suprofile.B2.GRA}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Merise</span></td>
		<td>{{ suprofile.B1.MER}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Microsoft Exchange Server</span></td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.M1.MSE}}</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Microsoft SharePoint Server</span></td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.M1.MOS}}</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Microsoft Technologies</span></td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.M1.NET}}</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">OSS</span></td>
		<td>{{ suprofile.B1.OSS}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Projet Dev</span></td>
		<td>{{ suprofile.B1.DEV}}</td>
		<td>{{ suprofile.B2.DEV}}</td>
		<td>{{ suprofile.B3.DEV}}</td>
		<td>{{ suprofile.M1.DEV}}</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Projet Architecture</span></td>
		<td>{{ suprofile.B1.ARC}}</td>
		<td>-</td>
		<td>{{ suprofile.B3.ARC}}</td>
		<td>{{ suprofile.M1.ARC}}</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Projet Web Dev</span></td>
		<td>-</td>
		<td>{{ suprofile.B2.DWB}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Réseau</span></td>
		<td>{{ suprofile.B1.CCNA}}</td>
		<td>{{ suprofile.B2.CNS}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">SQL</span></td>
		<td>{{ suprofile.B1.ORC}}</td>
		<td>{{ suprofile.B2.ORC}}</td>
		<td>{{ suprofile.B3.ORC}}</td>
		<td>-</td>
		<td>{{ suprofile.M2.ORC}}</td>
	</tr>
	<tr>
		<td><span class="coloration">Security</span></td>
		<td>{{ suprofile.B1.SEC}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Serveur Windows</span></td>
		<td>-</td>
		<td>{{ suprofile.B2.MSA}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Statistiques</span></td>
		<td>-</td>
		<td>{{ suprofile.B2.PBS}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Virtualization and IS Urbanization</span></td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.M1.VTZ}}</td>
		<td>{{ suprofile.M2.VTZ}}</td>
	</tr>
	<tr>
		<td><span class="coloration">VoIP</span></td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.M1.VIP}}</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Web</span></td>
		<td>{{ suprofile.B1.WEB}}</td>
		<td>{{ suprofile.B2.WEB}}</td>
		<td>{{ suprofile.B3.WEB}}</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Web Strategy</span></td>
		<td>{{ suprofile.B1.JWB}}</td>
		<td>{{ suprofile.B2.JWB}}</td>
		<td>-</td>
		<td>-</td>
		<td>-</td>
	</tr>
	<tr>
		<td><span class="coloration">Windows Active Directory</span></td>
		<td>-</td>
		<td>-</td>
		<td>{{ suprofile.B3.MSD}}</td>
		<td>-</td>
		<td>-</td>
	</tr>
</table>
{% endblock %}